name: Upload Python Package

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pypi-release-env
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'
    - name: Install build deps
      run: pip install --upgrade pip setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Install Twine
      run: pip install twine
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@release/v1

